services:
  rocky10build:
    volumes:
      - rpm10rocky:/home/centos/rpmbuild/RPMS
    build:
      context: .
      args:
        os: $RL10
        image: php-msgpack-8.1
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
  rocky9build:
    volumes:
      - rpm9rocky:/home/centos/rpmbuild/RPMS
    build:
      context: .
      args:
        os: $RL9
        image: php-msgpack-8.1
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0

volumes:
  rpm9rocky:
    name: rpm9rocky
  rpm10rocky:
    name: rpm10rocky
