ARG image=build

FROM aursu/pearbuild:6-${image}

RUN yum -y --enablerepo custom install \
        cyrus-sasl-devel \
        fastlz-devel \
        libevent2-devel \
        libmemcached-devel \
        php-pecl-igbinary-devel \
        php-pecl-msgpack-devel \
        zlib-devel \
    && yum clean all && rm -rf /var/cache/yum
