ARG centos=7
ARG image=build

FROM aursu/pearbuild:${centos}-${image}

RUN yum -y --enablerepo custom install \
        cyrus-sasl-devel \
        libevent-devel \
        libmemcached-devel \
        php-pecl-igbinary-devel \
        php-pecl-msgpack-devel \
        zlib-devel \
    && yum clean all && rm -rf /var/cache/yum
